### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Francy93** [AndesVL/vscode-racket-repl#11]
Hi guys!
I have to pay a compliment for this useful extension.
However, for some reason, it stopped working.
In fact, while trying to use it, it says "Command racket-repl.run" not found.

How could I solve it?

(Device Windows 10 pro)
(DrRacket is obviously installed)
(Racket directory in the system path)

**Comment by AndesVL** [comment]
Hi, 

I just published a new version (1.5.5).
Can you test again using this version? 

Did you update vscode recently?
Perhaps there is a version mismatch (I can't reproduce the error and I believe I'm running the newest version).

Kind regards, 

Andes

**Comment by Francy93** [comment]
VSCode version: 1.39.2 (latest)
Racket-repl version 1.5.5 (still not working :/)
![command](https://user-images.githubusercontent.com/57289592/68073566-76622080-fd89-11e9-98a8-4129941317a4.png)
![directory](https://user-images.githubusercontent.com/57289592/68073626-f6888600-fd89-11e9-830e-b65c7bba385c.png)

**Comment by AndesVL** [comment]
I believe something went wrong activating the extension but I don't know any details (I'm not an expert in vscode plugins).
I haven't encountered this error when testing the extension myself.

Perhaps you can try the following:

1.  Completely reinstall the extension.
     Uninstall it from vscode and make sure that the extension folder is effectively deleted (maybe delete the older version folders as well).

2. Install an older version of the extension.
   Extension marketplace > racket repl extension > install an older version > 1.3.0 (may work)

3. Clone this repository and compile/install the extension manually.

I don't really have time to look into this in too much detail today, maybe next week ;-)
Sorry for the inconvenience.

**Comment by Francy93** [comment]
I couldn't try the older version since I didn't find where to download it from.

Anyway, thank you for keeping this great extension updated and not to neglect it as many developers do, sadly. I hope next week I can somehow be helpful to fix it.  :)

Have a nice weekend!

**Comment by AndesVL** [comment]
Hi, 

You can download older versions within vscode itself (under the extension tab).
Perhaps version 1.3.0 works for you.

![image](https://user-images.githubusercontent.com/32360382/68074159-63a31800-fd98-11e9-8d81-7c1d44e0753d.png)

**Comment by AndesVL** [comment]
My friend encountered the same error in linux.

**Comment by Francy93** [comment]
We students from the Mdx University of London are cheering on you 🤞🤞🤞🤞🤞

**Comment by AndesVL** [comment]
On my friends pc, we got the repl extension running by removing the following extension: 

`https://marketplace.visualstudio.com/items?itemName=sjhuangx.vscode-scheme`

I'm not yet sure why the extensions clash.

Do you happen to have this extension installed as well?

**Comment by Francy93** [comment]
No, I don't have it.
![myExtensions](https://user-images.githubusercontent.com/57289592/68155552-d7345900-ff41-11e9-84a2-bb94e176fa61.png)
![myExtensionsDirectory](https://user-images.githubusercontent.com/57289592/68155553-d7345900-ff41-11e9-8bb1-23eec7cab226.png)

**Comment by AndesVL** [comment]
I installed all your extensions, and still can't reproduce D:

**Comment by Francy93** [comment]
hence, how to solve it?

**Comment by AndesVL** [comment]
I think I found the issue, try my new update.

**Comment by Francy93** [comment]
I think I definitely love you. Thank you 3000!!!!! <3 😍😍😍😍😍😍😍💘

What was the hidden bug?
![NowInLove](https://user-images.githubusercontent.com/57289592/68229349-ff2dc600-ffee-11e9-9c08-a1160815c077.png)

**Comment by Francy93** [comment]
Maybe, I just found a little further bug related to OneDrive! 😢

Probably it is due to spaces included in a folder name of the directory path (......\OneDrive - Middlesex University\\.....)
![BugFound](https://user-images.githubusercontent.com/57289592/68230121-6435eb80-fff0-11e9-8ce6-4ef23cd40f69.png)

**Comment by AndesVL** [comment]
I assumed that the vscode config contained a value for the integrated windows shell (powershell/cmd).
Apparently this value is only set after the user explicitly changes his default shell.
The fix was to default the plugin to "powershell.exe" on windows if the config was not set.

Regarding the second bug, I'll take a look at it later today. 
It may have something to with the spaces in the file path (oops ;p).

**Comment by Francy93** [comment]
Thanks for the great elucidation and for the time spent on these issues :))))
